// Generated by scripts/recovery/generate-shims.mjs. A compat shim is correct when every old name IS the owner's export.
import test from "node:test";
import assert from "node:assert/strict";
import * as shim0 from "../dist/index.js";
import * as owner0 from "obix-core-ssr";

test("obix-adapter-ssr: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim0["renderDocument"], owner0["renderDocument"], "renderDocument");
  assert.equal(shim0["renderToString"], owner0["renderToString"], "renderToString");
  assert.equal(shim0["toView"], owner0["toView"], "toView");
  assert.deepEqual(Object.keys(shim0).sort(), ["renderDocument","renderToString","toView"]);
  assert.equal("ComplianceError" in shim0, false, "ComplianceError is deliberately not carried over");
  assert.equal("compliance" in shim0, false, "compliance is deliberately not carried over");
  assert.equal("renderTrace" in shim0, false, "renderTrace is deliberately not carried over");
});
